services:
  - type: web
    name: aarogyalink
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 1 --bind 0.0.0.0:$PORT --timeout 120 server:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_DEBUG
        value: "false"
      - key: ADMIN_EMAIL
        value: admin@aarogyalink.in
      - key: ADMIN_PASSWORD
        value: Admin@2025#Secure
    disk:
      name: uploads
      mountPath: /opt/render/project/src/frontend/static/uploads
      sizeGB: 1